### PR TITLE
COMP: Improve const correctness for ValueIterators

### LINKED ISSUE #914: Issues compiling with uClibc++
I'm getting this error:

```
In file included from /home/mangix/devstuff/openwrt/build_dir/target-mips64_octeonplus_64_musl/jsoncpp-0.10.7/src/lib_json/json_value.cpp:153:0:
/home/mangix/devstuff/openwrt/build_dir/target-mips64_octeonplus_64_musl/jsoncpp-0.10.7/src/lib_json/json_valueiterator.inl: In member function 'Json::Value& Json::ValueIteratorBase::deref() const':
/home/mangix/devstuff/openwrt/build_dir/target-mips64_octeonplus_64_musl/jsoncpp-0.10.7/src/lib_json/json_valueiterator.inl:27:20: error: binding reference of type 'Json::Value&' to 'const Json::Value' discards qualifiers
   return current_->second;
          ~~~~~~~~~~^~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-mips64_octeonplus_64_musl/jsoncpp-0.10.7/src/lib_json/json_value.cpp: In member function 'const Json::Value& Json::Value::operator[](Json::Value::ArrayIndex) const':
/home/mangix/devstuff/openwrt/build_dir/target-mips64_octeonplus_64_musl/jsoncpp-0.10.7/src/lib_json/json_value.cpp:937:16: warning: returning reference to temporary [-Wreturn-local-addr]
   return (*it).second;
                ^~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-mips64_octeonplus_64_musl/jsoncpp-0.10.7/src/lib_json/json_value.cpp: In member function 'const Json::Value* Json::Value::find(const char*, const char*) const':
/home/mangix/devstuff/openwrt/build_dir/target-mips64_octeonplus_64_musl/jsoncpp-0.10.7/src/lib_json/json_value.cpp:1010:17: warning: taking address of temporary [-fpermissive]
   return &(*it).second;
                 ^~~~~~
```

### PR DESCRIPTION
**Pull request by hjmjohnson**
The protected deref method had inconsistent interface
of being a const function that returned a non-const
reference.  Resolves #914.

### CODE REVIEW

File: include/json/value.h [hunk 1]
```diff
@@ -895,9 +902,13 @@ class JSON_API ValueIterator : public ValueIteratorBase {
...
 
-  reference operator*() const { return deref(); }
-
-  pointer operator->() const { return &deref(); }
+  /*! The return value of non-const iterators can be
+   *  changed, so the these functions are not const
+   *  because the returned references/pointers can be used
+   *  to change state of the base class.
+   */
+  reference operator*() { return deref(); }
```
Comment (cdunn2001) [inline include/json/value.h]: Technically this broke binary compatibility, so this should have been a major version bump.

I guess we get away with this because probably nobody uses this method. If nobody complains, we can keep it.

**Comment by BillyDonahue** [comment]
I have to argue with the original premise of this change.

I did make the argument in the thread for issue #914 but received no response.

https://github.com/open-source-parsers/jsoncpp/issues/914#issuecomment-493570302

Iterators should model pointer. All standard container itererators do as well.

All 4 of these possiblities exist:

```
    T*
    const T*
    T*const
    const T*const
```

The constness of the pointer is independent of the constness of the thing to which it points.
Same with iterators.  `deref()` should continue to be const method of iterator.

The right signatures are:

```
Value& ValueIterator::deref() const;
const Value& ConstValueIterator::deref() const;
```
